In [1]:
import torch

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.arange(0, 128).unsqueeze(0).to(device)
x

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127]], device='cuda:0')

In [3]:
from nano_bert.model import DEBertAMix3
deberta = DEBertAMix3(
    vocab_size=4000, 
    n_layers=2,
    n_heads=1,
    max_seq_len=128,
    n_classes=2,
    n_embed = 4
).to('cuda')
deberta

DEBertAMix3(
  (nano_bert): NanoDEBERTA(
    (embedding): DEBertAEmbeddings(
      (word_embeddings): Embedding(4000, 3)
      (abposit_embeddings): AbsolutePositionEmbedding(
        (position_embeddings): Embedding(128, 1)
      )
    )
    (embedding_I): AbsolutePositionEmbedding(
      (position_embeddings): Embedding(128, 4)
    )
    (encoder): DEBertAEncoder(
      (layers): ModuleList(
        (0-1): 2 x DEBertALayer(
          (layer_norm1): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
          (self_attention): DEBertASelfAttention(
            (heads): ModuleList(
              (0): DEBertAAttentionHead(
                (query): Linear(in_features=4, out_features=4, bias=True)
                (key): Linear(in_features=4, out_features=4, bias=True)
                (values): Linear(in_features=4, out_features=4, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (proj): Linear(in_features=4, out_features=4, bia

In [4]:
deberta(x)

(tensor([[[-0.3222,  0.5652],
          [-0.1951,  0.3862],
          [-0.1208,  0.1932],
          [-0.3460,  0.5833],
          [-0.3988,  0.4120],
          [-0.0534, -0.0425],
          [-0.2873,  0.4567],
          [-0.3036,  0.5981],
          [ 0.0029, -0.2162],
          [-0.0177, -0.0952],
          [-0.0794,  0.0902],
          [-0.0474, -0.0710],
          [-0.1145,  0.1796],
          [-0.3349,  0.5837],
          [-0.0281, -0.1654],
          [-0.3288,  0.3921],
          [-0.0984,  0.1294],
          [-0.3528,  0.4894],
          [-0.3314,  0.3190],
          [-0.1189,  0.1821],
          [-0.3305,  0.3313],
          [-0.3352,  0.5089],
          [-0.3992,  0.3987],
          [ 0.1024, -0.3573],
          [-0.0594,  0.0350],
          [-0.2934,  0.2302],
          [-0.3764,  0.4625],
          [-0.3439,  0.4781],
          [-0.2956,  0.5446],
          [-0.0154, -0.1905],
          [-0.0908,  0.0743],
          [-0.1476,  0.2925],
          [-0.3554,  0.5706],
          

In [5]:
from nano_bert.model import ALBertMix3
albert = ALBertMix3(
    vocab_size=4000, 
    n_layers=2,
    n_heads=1,
    max_seq_len=128,
    n_classes=2,
    n_embed = 4
).to('cuda')
albert

ALBertMix3(
  (nano_bert): NanoALBERT(
    (embedding): ALBertEmbeddings(
      (hid_embeddings): Embedding(4000, 3)
      (word_embeddings): Linear(in_features=3, out_features=4, bias=True)
    )
    (position): PositionalEncoding(
      (layer_norm): LayerNorm((4,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): ALBertEncoder(
      (layer): BertLayer(
        (layer_norm1): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
        (self_attention): BertSelfAttention(
          (heads): ModuleList(
            (0): BertAttentionHead(
              (query): Linear(in_features=4, out_features=4, bias=True)
              (key): Linear(in_features=4, out_features=4, bias=True)
              (values): Linear(in_features=4, out_features=4, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (proj): Linear(in_features=4, out_features=4, bias=True)
          (dropout): Dropout(p=0.1, 

In [6]:
albert(x)

(tensor([[[ 0.5414,  0.1235],
          [ 0.2866,  0.2732],
          [ 0.5537,  0.1087],
          [ 0.3870,  0.2684],
          [ 0.4723,  0.1691],
          [ 0.5263,  0.1369],
          [ 0.1807,  0.3747],
          [ 0.2599,  0.3264],
          [ 0.2734,  0.3390],
          [ 0.2919,  0.2827],
          [ 0.6510, -0.0119],
          [ 0.5457,  0.1169],
          [ 0.5619,  0.0540],
          [ 0.6234,  0.0068],
          [ 0.4653,  0.1653],
          [ 0.4961,  0.2109],
          [ 0.6186,  0.0207],
          [ 0.4260,  0.2271],
          [ 0.2153,  0.3767],
          [ 0.5507,  0.0986],
          [ 0.2991,  0.3316],
          [ 0.3169,  0.3265],
          [ 0.2949,  0.2891],
          [ 0.2914,  0.3383],
          [ 0.4806,  0.1654],
          [ 0.5058,  0.0887],
          [ 0.5629,  0.0876],
          [ 0.6294,  0.0282],
          [ 0.2278,  0.3201],
          [ 0.5552,  0.0853],
          [ 0.4175,  0.2781],
          [ 0.2876,  0.3445],
          [ 0.4605,  0.1930],
          

In [7]:
from nano_bert.model import BertMix3
bert = BertMix3(
    vocab_size=4000, 
    n_layers=2,
    n_heads=1,
    max_seq_len=128,
    n_classes=2,
    n_embed = 4
).to('cuda')
bert

BertMix3(
  (nano_bert): NanoBERT(
    (embedding): BertEmbeddings(
      (word_embeddings): Embedding(4000, 4)
    )
    (position): PositionalEncoding(
      (layer_norm): LayerNorm((4,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layers): ModuleList(
        (0-1): 2 x BertLayer(
          (layer_norm1): LayerNorm((4,), eps=1e-05, elementwise_affine=True)
          (self_attention): BertSelfAttention(
            (heads): ModuleList(
              (0): BertAttentionHead(
                (query): Linear(in_features=4, out_features=4, bias=True)
                (key): Linear(in_features=4, out_features=4, bias=True)
                (values): Linear(in_features=4, out_features=4, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (proj): Linear(in_features=4, out_features=4, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [8]:
bert(x)

(tensor([[[ 0.1431, -0.3664],
          [-0.0870, -0.4700],
          [ 0.2277, -0.3561],
          [ 0.2409, -0.4794],
          [-0.0720, -0.3680],
          [ 0.3773, -0.5678],
          [ 0.3430, -0.2304],
          [ 0.2806, -0.8099],
          [ 0.1688, -0.3511],
          [ 0.3599, -0.5328],
          [ 0.2970, -0.2708],
          [ 0.1243, -0.1937],
          [ 0.1585, -0.6692],
          [-0.0499, -0.4190],
          [ 0.3581, -0.4448],
          [-0.0446, -0.3799],
          [ 0.2481, -0.7155],
          [ 0.1624, -0.1833],
          [ 0.0749, -0.6031],
          [ 0.3356, -0.0922],
          [ 0.3869, -0.6706],
          [ 0.0678, -0.5647],
          [ 0.3521, -0.4553],
          [-0.0739, -0.1826],
          [ 0.1065, -0.6615],
          [ 0.2971, -0.2462],
          [ 0.0519, -0.4746],
          [ 0.0342, -0.5341],
          [ 0.0426, -0.1848],
          [ 0.1547, -0.6279],
          [ 0.1968, -0.7223],
          [ 0.3018, -0.1164],
          [ 0.2497, -0.1246],
          